export default function borrar_datos_partida () {
    sessionStorage.removeItem('juego7reinas');
    sessionStorage.removeItem('pConectada7reinas');
    sessionStorage.removeItem('jugadorxs7reinas');
    sessionStorage.removeItem('jGetUser7reinas');
    sessionStorage.removeItem('miturno7reinas');
    sessionStorage.removeItem('mano7reinas');
    sessionStorage.removeItem('tablero7reinas');
    sessionStorage.removeItem('descarte7reinas');
    sessionStorage.removeItem('turno7reinas');
    sessionStorage.removeItem('heabierto7reinas');
    sessionStorage.removeItem('herobado7reinas');
    sessionStorage.removeItem("es_torneo7reinas");
    sessionStorage.removeItem("puntosTorneo7reinas");
    sessionStorage.removeItem("ganadorxronda7reinas");
    sessionStorage.removeItem("ganadorx7reinas");
    sessionStorage.removeItem("torneo_ganado7reinas");
    sessionStorage.removeItem("reanudada7reinas");    
}