export default function logOut () {
    sessionStorage.removeItem('usuario7reinas');
    sessionStorage.removeItem('amigxs7reinas');
    sessionStorage.removeItem('solicitudes7reinas');
    sessionStorage.removeItem('mensajes7reinas');
    sessionStorage.removeItem('msjsjuego7reinas');
    sessionStorage.removeItem('juego7reinas');
    sessionStorage.removeItem('pConectada7reinas');
    sessionStorage.removeItem('jugadorxs7reinas');
    sessionStorage.removeItem('jGetUser7reinas');
    sessionStorage.removeItem('miturno7reinas');
    sessionStorage.removeItem('mano7reinas');
    sessionStorage.removeItem('tablero7reinas');
    sessionStorage.removeItem('descarte7reinas');
    sessionStorage.removeItem('turno7reinas');
    sessionStorage.removeItem('heabierto7reinas');
    sessionStorage.removeItem('herobado7reinas');
    sessionStorage.removeItem('part_pausadas7reinas');
    sessionStorage.removeItem("es_torneo7reinas");
    sessionStorage.removeItem("puntosTorneo7reinas");
    sessionStorage.removeItem("ganadorxronda7reinas");
    sessionStorage.removeItem("ganadorx7reinas");
    sessionStorage.removeItem("torneo_ganado7reinas");
    sessionStorage.removeItem("reanudada7reinas");
    sessionStorage.removeItem("anfitrion7reinas");
    localStorage.removeItem('sesionrecordada7reinas');
}